kind: Service
apiVersion: v1
metadata:
  name: node-exporter-dispatcher
spec:
  type: NodePort
  selector:
    name: node-exporter-dispatcher
  ports:
  - port: 9100
    targetPort: 9100
    protocol: TCP
    nodePort: 32000
---

kind: Service
apiVersion: v1
metadata:
  name: node-exporter-worker-0
spec:
  type: NodePort
  selector:
    name: node-exporter-worker-0
  ports:
  - port: 9100
    targetPort: 9100
    protocol: TCP
    nodePort: 32001
---

kind: Service
apiVersion: v1
metadata:
  name: node-exporter-worker-1
spec:
  type: NodePort
  selector:
    name: node-exporter-worker-1
  ports:
  - port: 9100
    targetPort: 9100
    protocol: TCP
    nodePort: 32002
---

kind: Service
apiVersion: v1
metadata:
  name: node-exporter-worker-2
spec:
  type: NodePort
  selector:
    name: node-exporter-worker-2
  ports:
  - port: 9100
    targetPort: 9100
    protocol: TCP
    nodePort: 32003
---

kind: Service
apiVersion: v1
metadata:
  name: node-exporter-worker-3
spec:
  type: NodePort
  selector:
    name: node-exporter-worker-3
  ports:
  - port: 9100
    targetPort: 9100
    protocol: TCP
    nodePort: 32004
---

