version: '2.3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./www:/var/www
      - ./conf.d:/etc/nginx/conf.d
      - ./logs:/usr/local/nginx/logs
    network_mode: "host"
