version: '2.3'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus2
    restart: always
    ports:
      - 9091:9090
    volumes:
      - ./prometheus-config:/etc/prometheus
      - ./prometheus-data:/prometheus
